### ISSUE TITLE
Hunpos does not tag properly when input/output is piped to/from file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mivoq/hunpos#12]
```
I am running Hunpos 1.0 on Windows XP, using the provided english-wsj 
model. Hunpos works great when I use it interactively, but when I pipe 
input/output to/from file, the tags are all obviously wrong.

Here is my input file (in.txt):

The
quick
red
fox
jumped
over
the
lazy
dogs.

>hunpos-tag english.model <in.txt >out.txt

This is what I get in out.txt:

The
	NNP	
quick
	VBD	
red
	CD	
fox
	CD	
jumped
	CD	
over
	CD	
the
	CD	
lazy
	CD	
dogs.
	JJ	

	NNS	

If I type the same text in manually at the console, the resulting tags are 
completely different.

What gives?

Thanks in advance... Alex Dowad
```

Original issue reported on code.google.com by `alexinbe...@gmail.com` on 18 Feb 2010 at 12:06

**Comment by giuliopaci** [comment]
I can confirm that using \r\n line terminators, will make hunpos-tag fail to predict tags. This is due to the fact that the input format of hunpos-tag is <token_string>\n and not <token_string>\r\n.
For this reason \r is treated as part of the <token_string>, thus making it an unknown word, with weird suffix (so that it is even hard to predict anything based on the morphology as well).
