### ISSUE TITLE
tagging erroneous in some cases

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mivoq/hunpos#16]
```
What steps will reproduce the problem?
Tag a sample corpus


What is the expected output? What do you see instead?
I wrote in for example:
       got       expected
I	PRP	
do	VBP	
work	NN	<-- VB
.	SENT	


What version of the product are you using? On what operating system?
1.2.8, linux mint

Please provide any additional information below.


```

Original issue reported on code.google.com by `krie...@gmx.de` on 19 Dec 2010 at 8:59

**Comment by giuliopaci** [comment]
This is implicit with the task. It is impossible to have perfect result (there are ambiguous cases, for example).
Specific models can be improved (and this is out-of-topic here) or the methodology can be improved (and this is on-topic). So, if the issue can be formulated as "there is an unexpected errors that is due to this error in the methodology", it can be accepted here, otherwise it cannot.
